server:
  servlet:
    context-path: /auth
  port: 8081

spring:
  application:
    name: auth

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  key: ${JWT_KEY}
  valid-duration: 7200 # seconds
  refresh-duration: 1209600 # seconds

user-service:
  url: http://localhost:8082/users

logging:
  level:
    org:
      springframework: DEBUG