server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2

        - id: profile_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2

        - id: post_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/posts/**
          filters:
            - StripPrefix=2
