server:
  servlet:
    context-path: /users
  port: 8082

spring:
  application:
    name: user

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_service
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

logging:
  level:
    org:
      springframework: DEBUG
